name: word-to-pdf-bundle

services:
  php:
    build: .
    command: ["sleep", "infinity"]
    volumes:
      - .:/app
      - coverage-data:/app/var/coverage
    working_dir: /app

volumes:
  coverage-data: {}
