name: word-to-pdf-bundle

services:
  php:
    build: .
    command: ["sleep", "infinity"]
    volumes:
      - .:/app
      - coverage-data:/app/var/coverage
    working_dir: /app
    networks:
      - word-to-pdf-dev

volumes:
  coverage-data: {}

networks:
  word-to-pdf-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 10.250.82.0/24
